#!/bin/bash
# generated by AI
# Usage: ./tweak.sh remove_zero_width_space source/_posts/python-magic-func.md

# 移除文件中的零宽度空格(U+200B)
remove_zero_width_space() {
    local input_file="$1"
    
    # 检查输入文件是否存在
    if [ ! -f "$input_file" ]; then
        echo "错误: 文件 '$input_file' 不存在"
        return 1
    fi
    
    # 执行替换操作，使用临时文件避免直接修改原文件
    local temp_file=$(mktemp)
    
    # 移除零宽度空格(\xe2\x80\x8b)并保存到临时文件
    sed 's/\xe2\x80\x8b//g' "$input_file" > "$temp_file"
    
    # 将临时文件内容覆盖回原文件
    mv "$temp_file" "$input_file"
    
    echo "已成功移除文件 '$input_file' 中的所有零宽度空格"
    return 0
}

# 主程序：解析命令行参数并调用相应函数
if [ $# -ne 2 ]; then
    echo "用法: $0 函数名 输入文件"
    echo "可用函数:"

    echo "  remove_zero_width_space: 移除文件中的零宽度空格(U+200B)"
    exit 1
fi

function_name="$1"
input_file="$2"

# 检查函数是否存在并调用
if declare -f "$function_name" > /dev/null; then
    "$function_name" "$input_file"
else
    echo "错误: 函数 '$function_name' 不存在"
    echo "可用函数: remove_zero_width_space"
    exit 1
fi

